Control the dirs where include files are
To avoid this compile problem:

  utils/../constants/defs.h:31:13: fatal error: 'fftw3.h' file not found

We need to search for fftw3.h in the usual places, so we
added the makefile variable LOC_INC which by default is:

    -I /usr/global/include -I /usr/local/include

Thus fftw3.h will be search for in the following places:

    /usr/global/include/fftw3.h
    /usr/local/include/fftw3.h
    /usr/include/fftw3.h

The first file that is found will be used.

If for some reason, fftw3.h is placed in some strange location,
the user can do the following:

    make 'LOC_INC= -I /some/odd/include/path'

NOTE: There is no error or warning of either /usr/global/include
      or /usr/local/include directories do not exist.